work: /scratch1/mce03b/2020-02-28_GWAS

reads:
    R1:
    R2:

samples:
    15FL1-2:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15FL1-2    
    15Fl1-4:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15Fl1-4
    15MN10-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN10-4
    15MN10-5: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN10-5
    15MN13-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN13-4
    15MN14-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN14-4
    15MN15-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN15-3
    15MN16-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN16-3
    15MN17-5: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN17-5
    15MN18-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN18-1
    15MN18-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN18-3
    15MN23-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN23-1
    15MN24-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN24-1
    15MN25-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN25-3
    15MN27-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MN27-3
    15MS7-1:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15MS7-1
    15ND19-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15ND19-2
    15ND19-5: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15ND19-5
    15ND20-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15ND20-3
    15ND20-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15ND20-4
    15NE8-4:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15NE8-4
    15NE8-5:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15NE8-5
    15NE9-1:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15NE9-1
    15NE9-3:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15NE9-3
    15OH12-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15OH12-3
    15SD11-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15SD11-1
    15SD11-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15SD11-2
    15SD30-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15SD30-1
    15SD30-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15SD30-3
    15TX3-1:  /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/15TX3-1
    16IL75-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16IL75-3
    16MN100-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN100-2
    16MN101-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN101-1
    16MN102-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN102-1
    16MN102-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN102-3
    16MN105-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN105-1
    16MN106-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN106-3
    16MN107-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN107-1
    16MN107-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN107-3
    16MN110-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN110-1
    16MN110-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN110-2
    16MN118-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN118-2
    16MN119-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN119-1
    16MN121-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN121-2
    16MN84-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN84-1
    16MN85-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN85-1
    16MN88-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN88-3
    16MN90-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN90-2
    16MN93-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN93-1
    16MN93-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN93-2
    16MN94-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN94-1
    16MN94-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN94-2
    16MN98-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN98-2
    16MN98-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN98-3
    16MN99-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN99-1
    16MN99-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN99-2
    16MN99-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16MN99-3
    16SD69-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16SD69-1
    16SD74-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16SD74-2
    16WI76-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/16WI76-1
    17AR69-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17AR69-3
    17FL20-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL20-1
    17FL20-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL20-2
    17FL20-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL20-3
    17FL21-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL21-2
    17FL22-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL22-2
    17FL23-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL23-1
    17FL23-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17FL23-2
    17IA105-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA105-1
    17IA106-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA106-3
    17IA108-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA108-2
    17IA109-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA109-3
    17IA111-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA111-3
    17IA116-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IA116-1
    17IL75-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IL75-3
    17IL76-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IL76-1
    17IL76-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17IL76-3
    17LA48-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17LA48-2
    17LA49-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17LA49-3
    17LA50-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17LA50-2
    17LA50-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17LA50-3
    17LA67-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17LA67-2
    17MN145-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN145-1
    17MN145-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN145-2
    17MN146-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN146-1
    17MN146-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN146-2
    17MN150-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN150-1
    17MN150-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN150-2
    17MN78-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MN78-2
    17MNBT-10: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-10
    17MNBT-11: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-11
    17MNBT-12: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-12
    17MNBT-13: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-13
    17MNBT-14: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-14
    17MNBT-15: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-15
    17MNBT-16: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-16
    17MNBT-17: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-17
    17MNBT-18: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-18
    17MNBT-19: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-19
    17MNBT-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-2
    17MNBT-20: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-20
    17MNBT-21: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-21
    17MNBT-23: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-23
    17MNBT-24: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-24
    17MNBT-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-3
    17MNBT-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-4
    17MNBT-5: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-5
    17MNBT-6: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-6
    17MNBT-7: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-7
    17MNBT-8: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-8
    17MNBT-9: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MNBT-9
    17MS65-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MS65-1
    17MS65-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17MS65-3
    17SD126-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD126-1
    17SD126-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD126-2
    17SD126-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD126-3
    17SD129-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD129-3
    17SD132-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD132-1
    17SD133-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD133-2
    17SD79-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD79-2
    17SD80-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17SD80-2
    17TX1-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX1-2
    17TX12-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX12-3
    17TX15-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX15-3
    17TX44-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX44-3
    17TX59-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX59-2
    17TX62-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX62-3
    17TX9-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/17TX9-2
    18MNBT-34: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-34
    18MNBT-35: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-35
    18MNBT-36: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-36
    18MNBT-37: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-37
    18MNBT-38: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-38
    18MNBT-39: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-39
    18MNBT-40: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-40
    18MNBT-41: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-41
    18MNBT-42: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-42
    18MNBT-43: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-43
    18MNBT-44: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-44
    18MNBT-45: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-45
    18MNBT-46: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-46
    18MNBT-47: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-47
    18MNBT-49: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-49
    18MNBT-50: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-50
    18MNBT-51: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-51
    18MNBT-52: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-52
    18MNBT-53: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-53
    18MNBT-54: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-54
    18MNBT-55: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-55
    18MNBT-56: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-56
    18MNBT-57: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-57
    18MNBT-58: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/18MNBT-58
    90AR100-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90AR100-1
    90GA16-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90GA16-1
    90KS101-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90KS101-1
    90LA38-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90LA38-1
    90MN137-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN137-1
    90MN13B-3: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN13B-3
    90MN148-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN148-1
    90MN149-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN149-2
    90MN14B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN14B-1
    90MN152-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN152-1
    90MN153-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN153-1
    90MN17B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN17B-1
    90MN1B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN1B-1
    90MN2B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN2B-1
    90MN3B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN3B-1
    90MN5B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN5B-1
    90MN7B-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN7B-1
    90MN8B-2: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN8B-2
    90MN9B-4: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90MN9B-4
    90PA162-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90PA162-1
    90SD164-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90SD164-1
    90SD171-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90SD171-1
    90SD172-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90SD172-1
    90TX45-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90TX45-1
    90TX47-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90TX47-1
    90TX52-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90TX52-1
    90TX58-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90TX58-1
    90TX70-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90TX70-1
    90WI131-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90WI131-1
    90WI132-1: /datasets/work/AF_CROWN_RUST_WORK/2020-02-28_GWAS/data/90WI132-1

refs:
    12NC29: GCA_002873275.1_ASM287327v1_genomic
    12SD80: GCA_002873125.1_ASM287312v1_genomic 
